2023-04-05 22:55:22,719 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (3,)
Traceback (most recent call last):
  File "c:\Users\siddr\anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1134, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 594, in numpy.random._common.cont
  File "_common.pyx", line 511, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 3) and arg 1 with shape (10, 2).
2023-04-05 22:55:42,179 - pyswarms.single.global_best - INFO - Optimize for 20 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2023-04-05 22:55:42,364 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -1.0, best pos: [1.67117679 0.33547855]
2023-04-05 23:32:21,293 - pyswarms.single.global_best - INFO - Optimize for 20 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2023-04-05 23:32:21,496 - pyswarms.single.global_best - INFO - Optimization finished | best cost: -1.0, best pos: [4.19919425]
